In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

RAW_DATA_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DATA_DIR = BASE_DIR / "data" / "processed"

print("Base directory:", BASE_DIR)
print("Raw data directory:", RAW_DATA_DIR)
print("Processed data directory:", PROCESSED_DATA_DIR)

Base directory: c:\Users\Charith\Desktop\My Projects\Global-AI-Data-Science-Skills-and-Salary-Trends
Raw data directory: c:\Users\Charith\Desktop\My Projects\Global-AI-Data-Science-Skills-and-Salary-Trends\data\raw
Processed data directory: c:\Users\Charith\Desktop\My Projects\Global-AI-Data-Science-Skills-and-Salary-Trends\data\processed

In [3]:
ai_jobs = pd.read_csv(RAW_DATA_DIR / "ai_jobs.csv")
country_trends = pd.read_csv(RAW_DATA_DIR / "country_ai_trends.csv")
skills_demand = pd.read_csv(RAW_DATA_DIR / "skills_demand.csv")
job_mapping = pd.read_csv(RAW_DATA_DIR / "job_title_mapping.csv")
data_dictionary = pd.read_csv(RAW_DATA_DIR / "data_dictionary.csv")

print("CSV files loaded successfully")

CSV files loaded successfully

In [4]:
print("ai_jobs:", ai_jobs.shape)
print("country_trends:", country_trends.shape)
print("skills_demand:", skills_demand.shape)
print("job_mapping:", job_mapping.shape)
print("data_dictionary:", data_dictionary.shape)

ai_jobs: (50000, 14)
country_trends: (42, 6)
skills_demand: (224605, 4)
job_mapping: (6, 3)
data_dictionary: (13, 3)

In [5]:
print("ai_jobs columns:")
print(ai_jobs.columns.tolist())

print("\ncountry_trends columns:")
print(country_trends.columns.tolist())

print("\nskills_demand columns:")
print(skills_demand.columns.tolist())

print("\njob_mapping columns:")
print(job_mapping.columns.tolist())

print("\ndata_dictionary columns:")
print(data_dictionary.columns.tolist())

ai_jobs columns:
['job_id', 'job_title', 'company_type', 'industry', 'country', 'city', 'remote_type', 'experience_level', 'min_experience_years', 'salary_min_usd', 'salary_max_usd', 'employment_type', 'posted_year', 'company_size']

country_trends columns:
['country', 'year', 'total_ai_jobs', 'avg_salary_usd', 'remote_percentage', 'top_skill']

skills_demand columns:
['job_id', 'skill', 'skill_category', 'skill_level']

job_mapping columns:
['job_title', 'standardized_title', 'role_category']

data_dictionary columns:
['file', 'column', 'description']

In [6]:
ai_jobs.head()

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2,102977,127298,Full-time,2023,Large

In [7]:
skills_demand.head()

         job_id            skill skill_category   skill_level
0  E0IFD0TVBDIV                R    Programming      Advanced
1  E0IFD0TVBDIV  Computer Vision             ML         Basic
2  E0IFD0TVBDIV              NLP             ML  Intermediate
3  E0IFD0TVBDIV              SQL    Programming  Intermediate
4  ZMF8MDD4V30T              NLP             ML      Advanced

In [8]:
country_trends.head()

  country  year  total_ai_jobs  avg_salary_usd  remote_percentage top_skill
0     USA  2020          78050          109581                 81    Python
1     USA  2021           5322          116022                 30    Python
2     USA  2022          55204          157026                 39       GCP
3     USA  2023          42906          139108                 25       GCP
4     USA  2024          18847          103070                 63       AWS

In [9]:
print("Missing values in ai_jobs:")
print(ai_jobs.isnull().sum())

print("\nMissing values in skills_demand:")
print(skills_demand.isnull().sum())

print("\nMissing values in country_trends:")
print(country_trends.isnull().sum())

Missing values in ai_jobs:
job_id                  0
job_title               0
company_type            0
industry                0
country                 0
city                    0
remote_type             0
experience_level        0
min_experience_years    0
salary_min_usd          0
salary_max_usd          0
employment_type         0
posted_year             0
company_size            0
dtype: int64

Missing values in skills_demand:
job_id            0
skill             0
skill_category    0
skill_level       0
dtype: int64

Missing values in country_trends:
country              0
year                 0
total_ai_jobs        0
avg_salary_usd       0
remote_percentage    0
top_skill            0
dtype: int64

In [10]:
print("Duplicate rows in ai_jobs:", ai_jobs.duplicated().sum())
print("Duplicate rows in skills_demand:", skills_demand.duplicated().sum())
print("Duplicate rows in country_trends:", country_trends.duplicated().sum())

Duplicate rows in ai_jobs: 0
Duplicate rows in skills_demand: 0
Duplicate rows in country_trends: 0

In [11]:
print("ai_jobs data types:")
print(ai_jobs.dtypes)

print("\nskills_demand data types:")
print(skills_demand.dtypes)

print("\ncountry_trends data types:")
print(country_trends.dtypes)

ai_jobs data types:
job_id                    str
job_title                 str
company_type              str
industry                  str
country                   str
city                      str
remote_type               str
experience_level          str
min_experience_years    int64
salary_min_usd          int64
salary_max_usd          int64
employment_type           str
posted_year             int64
company_size              str
dtype: object

skills_demand data types:
job_id            str
skill             str
skill_category    str
skill_level       str
dtype: object

country_trends data types:
country                str
year                 int64
total_ai_jobs        int64
avg_salary_usd       int64
remote_percentage    int64
top_skill              str
dtype: object

In [12]:
print("Salary statistics from ai_jobs:")
print(ai_jobs[["salary_min_usd", "salary_max_usd"]].describe())

print("\nAverage salary statistics from country_trends:")
print(country_trends["avg_salary_usd"].describe())

Salary statistics from ai_jobs:
       salary_min_usd  salary_max_usd
count    50000.000000    50000.000000
mean    100871.434320   120858.350740
std      37043.446641    37531.386484
min      50000.000000    65000.000000
25%      61287.000000    83739.000000
50%      97505.000000   117604.000000
75%     143730.500000   161348.750000
max     154999.000000   180000.000000

Average salary statistics from country_trends:
count        42.000000
mean     124777.904762
std       26730.806794
min       76942.000000
25%      108012.750000
50%      131059.000000
75%      143991.000000
max      164795.000000
Name: avg_salary_usd, dtype: float64

In [13]:
ai_jobs["salary_avg_usd"] = (ai_jobs["salary_min_usd"] + ai_jobs["salary_max_usd"]) / 2

ai_jobs[["salary_min_usd", "salary_max_usd", "salary_avg_usd"]].head()

   salary_min_usd  salary_max_usd  salary_avg_usd
0           56873           72223         64548.0
1           54803           85599         70201.0
2          149980          175806        162893.0
3           53483           86477         69980.0
4          102977          127298        115137.5

In [14]:
print("Remote Types:")
print(ai_jobs["remote_type"].unique())

print("\nExperience Levels:")
print(ai_jobs["experience_level"].unique())

print("\nEmployment Types:")
print(ai_jobs["employment_type"].unique())

print("\nCompany Sizes:")
print(ai_jobs["company_size"].unique())

print("\nPosted Years:")
print(sorted(ai_jobs["posted_year"].unique()))

Remote Types:
<StringArray>
['Remote', 'Hybrid', 'Onsite']
Length: 3, dtype: str

Experience Levels:
<StringArray>
['Entry', 'Senior', 'Mid']
Length: 3, dtype: str

Employment Types:
<StringArray>
['Full-time']
Length: 1, dtype: str

Company Sizes:
<StringArray>
['Large', 'Medium', 'Small']
Length: 3, dtype: str

Posted Years:
[np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

In [15]:
print("Top 10 Countries:")
print(ai_jobs["country"].value_counts().head(10))

print("\nTop 10 Job Titles:")
print(ai_jobs["job_title"].value_counts().head(10))

print("\nTop 10 Industries:")
print(ai_jobs["industry"].value_counts().head(10))

Top 10 Countries:
country
UK           8452
India        8350
Germany      8345
Canada       8303
Australia    8276
USA          8274
Name: count, dtype: int64

Top 10 Job Titles:
job_title
MLOps Engineer               8439
AI Researcher                8415
Data Scientist               8410
Applied Scientist            8298
Data Analyst                 8260
Machine Learning Engineer    8178
Name: count, dtype: int64

Top 10 Industries:
industry
Tech          10083
Healthcare    10029
Retail         9979
Finance        9970
Education      9939
Name: count, dtype: int64

In [16]:
print("Top 15 Skills:")
print(skills_demand["skill"].value_counts().head(15))

print("\nSkill Categories:")
print(skills_demand["skill_category"].value_counts())

print("\nSkill Levels:")
print(skills_demand["skill_level"].value_counts())

Top 15 Skills:
skill
AWS                20638
GCP                20552
TensorFlow         20552
Azure              20517
Scikit-learn       20511
NLP                20414
Python             20396
SQL                20322
Computer Vision    20313
R                  20205
PyTorch            20185
Name: count, dtype: int64

Skill Categories:
skill_category
ML             101975
Cloud           61707
Programming     60923
Name: count, dtype: int64

Skill Levels:
skill_level
Basic           74992
Intermediate    74920
Advanced        74693
Name: count, dtype: int64

In [17]:
print("Country Trends Preview:")
display(country_trends.head())

print("\nYears in country_trends:")
print(sorted(country_trends["year"].unique()))

print("\nCountries in country_trends:")
print(country_trends["country"].unique())

print("\nTotal AI jobs by year:")
print(country_trends.groupby("year")["total_ai_jobs"].sum())

print("\nAverage salary by year:")
print(country_trends.groupby("year")["avg_salary_usd"].mean())

Country Trends Preview:

  country  year  total_ai_jobs  avg_salary_usd  remote_percentage top_skill
0     USA  2020          78050          109581                 81    Python
1     USA  2021           5322          116022                 30    Python
2     USA  2022          55204          157026                 39       GCP
3     USA  2023          42906          139108                 25       GCP
4     USA  2024          18847          103070                 63       AWS

Years in country_trends:
[np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

Countries in country_trends:
<StringArray>
['USA', 'India', 'Germany', 'UK', 'Canada', 'Australia']
Length: 6, dtype: str

Total AI jobs by year:
year
2020    343314
2021    245414
2022    208282
2023    207551
2024    250318
2025    199930
2026    279713
Name: total_ai_jobs, dtype: int64

Average salary by year:
year
2020    131143.333333
2021    113774.333333
2022    132642.000000
2023    134216.333333
2024    122411.000000
2025    124712.000000
2026    114546.333333
Name: avg_salary_usd, dtype: float64

## Data Quality Check Summary

The dataset was checked for missing values, duplicate records, data types, salary statistics, and key categorical values.

Key findings:
- No missing values were found in the main datasets.
- No duplicate rows were found.
- Salary and year columns are stored as numeric data types.
- The dataset covers job market data from 2020 to 2026.
- Remote types include Remote, Hybrid, and Onsite.
- Experience levels include Entry, Mid, and Senior.
- Employment type contains only Full-time roles, so it will not be used for major comparison.
- The main countries are USA, India, Germany, UK, Canada, and Australia.
- The main job titles are MLOps Engineer, AI Researcher, Data Scientist, Applied Scientist, Data Analyst, and Machine Learning Engineer.
- The main industries are Tech, Healthcare, Retail, Finance, and Education.
- The main skill categories are ML, Cloud, and Programming.
- Country trend data shows that AI/Data Science job demand fluctuated from 2020 to 2026, with a recovery in 2026.

In [18]:
def categorize_salary(salary):
    if salary < 80000:
        return "Low"
    elif salary < 120000:
        return "Medium"
    elif salary < 150000:
        return "High"
    else:
        return "Very High"

ai_jobs["salary_level"] = ai_jobs["salary_avg_usd"].apply(categorize_salary)

ai_jobs[["salary_avg_usd", "salary_level"]].head()

   salary_avg_usd salary_level
0         64548.0          Low
1         70201.0          Low
2        162893.0    Very High
3         69980.0          Low
4        115137.5       Medium

In [19]:
def create_career_stage(level):
    if level == "Entry":
        return "Entry Level"
    elif level == "Mid":
        return "Mid Level"
    elif level == "Senior":
        return "Senior Level"
    else:
        return "Unknown"

ai_jobs["career_stage"] = ai_jobs["experience_level"].apply(create_career_stage)

ai_jobs[["experience_level", "career_stage"]].head()

  experience_level  career_stage
0            Entry   Entry Level
1            Entry   Entry Level
2           Senior  Senior Level
3            Entry   Entry Level
4              Mid     Mid Level

In [20]:
def remote_friendly(remote_type):
    if remote_type in ["Remote", "Hybrid"]:
        return "Yes"
    elif remote_type == "Onsite":
        return "No"
    else:
        return "Unknown"

ai_jobs["is_remote_friendly"] = ai_jobs["remote_type"].apply(remote_friendly)

ai_jobs[["remote_type", "is_remote_friendly"]].head()

  remote_type is_remote_friendly
0      Remote                Yes
1      Remote                Yes
2      Remote                Yes
3      Remote                Yes
4      Hybrid                Yes

In [21]:
def create_role_group(job_title):
    if job_title == "Data Analyst":
        return "Data Analytics"
    elif job_title == "Data Scientist":
        return "Data Science"
    elif job_title == "Machine Learning Engineer":
        return "Machine Learning"
    elif job_title == "MLOps Engineer":
        return "MLOps"
    elif job_title == "AI Researcher":
        return "AI Research"
    elif job_title == "Applied Scientist":
        return "Applied AI / Research"
    else:
        return "Other"

ai_jobs["role_group"] = ai_jobs["job_title"].apply(create_role_group)

ai_jobs[["job_title", "role_group"]].head()

                   job_title             role_group
0             MLOps Engineer                  MLOps
1               Data Analyst         Data Analytics
2             MLOps Engineer                  MLOps
3          Applied Scientist  Applied AI / Research
4  Machine Learning Engineer       Machine Learning

In [22]:
ai_jobs[[
    "job_title",
    "role_group",
    "experience_level",
    "career_stage",
    "remote_type",
    "is_remote_friendly",
    "salary_avg_usd",
    "salary_level"
]].head(10)

,job_title,role_group,experience_level,career_stage,remote_type,is_remote_friendly,salary_avg_usd,salary_level
0,MLOps Engineer,MLOps,Entry,Entry Level,Remote,Yes,64548.0,Low
1,Data Analyst,Data Analytics,Entry,Entry Level,Remote,Yes,70201.0,Low
2,MLOps Engineer,MLOps,Senior,Senior Level,Remote,Yes,162893.0,Very High
3,Applied Scientist,Applied AI / Research,Entry,Entry Level,Remote,Yes,69980.0,Low
4,Machine Learning Engineer,Machine Learning,Mid,Mid Level,Hybrid,Yes,115137.5,Medium
5,Data Analyst,Data Analytics,Senior,Senior Level,Hybrid,Yes,164084.0,Very High
6,AI Researcher,AI Research,Senior,Senior Level,Onsite,No,158768.5,Very High
7,MLOps Engineer,MLOps,Senior,Senior Level,Hybrid,Yes,159568.0,Very High
8,Machine Learning Engineer,Machine Learning,Entry,Entry Level,Remote,Yes,72781.0,Low
9,Machine Learning Engineer,Machine Learning,Entry,Entry Level,Hybrid,Yes,63471.5,Low

In [23]:
ai_jobs.to_csv(PROCESSED_DATA_DIR / "ai_jobs_cleaned.csv", index=False)
skills_demand.to_csv(PROCESSED_DATA_DIR / "skills_demand_cleaned.csv", index=False)
country_trends.to_csv(PROCESSED_DATA_DIR / "country_trends_cleaned.csv", index=False)

print("Cleaned CSV files saved successfully")

Cleaned CSV files saved successfully

In [24]:
jobs_by_year = ai_jobs.groupby("posted_year")["job_id"].count().reset_index()

jobs_by_year.columns = ["posted_year", "job_count"]

jobs_by_year

   posted_year  job_count
0         2020       7205
1         2021       7128
2         2022       7135
3         2023       7035
4         2024       7312
5         2025       7043
6         2026       7142

In [25]:
jobs_by_country = ai_jobs.groupby("country")["job_id"].count().reset_index()

jobs_by_country.columns = ["country", "job_count"]

jobs_by_country = jobs_by_country.sort_values(by="job_count", ascending=False)

jobs_by_country

     country  job_count
4         UK       8452
3      India       8350
2    Germany       8345
1     Canada       8303
0  Australia       8276
5        USA       8274

In [26]:
jobs_by_role = ai_jobs.groupby("role_group")["job_id"].count().reset_index()

jobs_by_role.columns = ["role_group", "job_count"]

jobs_by_role = jobs_by_role.sort_values(by="job_count", ascending=False)

jobs_by_role

              role_group  job_count
4                  MLOps       8439
0            AI Research       8415
3           Data Science       8410
1  Applied AI / Research       8298
2         Data Analytics       8260
5       Machine Learning       8178

In [27]:
salary_by_role = ai_jobs.groupby("role_group")["salary_avg_usd"].mean().reset_index()

salary_by_role.columns = ["role_group", "avg_salary_usd"]

salary_by_role = salary_by_role.sort_values(by="avg_salary_usd", ascending=False)

salary_by_role

              role_group  avg_salary_usd
1  Applied AI / Research   111382.242167
2         Data Analytics   111343.315133
5       Machine Learning   110816.692345
3           Data Science   110740.231570
0            AI Research   110574.632620
4                  MLOps   110348.288541

In [28]:
salary_by_country = ai_jobs.groupby("country")["salary_avg_usd"].mean().reset_index()

salary_by_country.columns = ["country", "avg_salary_usd"]

salary_by_country = salary_by_country.sort_values(by="avg_salary_usd", ascending=False)

salary_by_country

     country  avg_salary_usd
0  Australia   111485.412337
5        USA   111057.537165
4         UK   111039.290582
2    Germany   110897.890294
3      India   110396.954910
1     Canada   110314.312839

In [29]:
salary_by_career_stage = ai_jobs.groupby("career_stage")["salary_avg_usd"].mean().reset_index()

salary_by_career_stage.columns = ["career_stage", "avg_salary_usd"]

salary_by_career_stage = salary_by_career_stage.sort_values(by="avg_salary_usd", ascending=False)

salary_by_career_stage

   career_stage  avg_salary_usd
2  Senior Level   157490.178359
1     Mid Level   107507.124049
0   Entry Level    67473.507698

In [30]:
jobs_by_remote_type = ai_jobs.groupby("remote_type")["job_id"].count().reset_index()

jobs_by_remote_type.columns = ["remote_type", "job_count"]

jobs_by_remote_type = jobs_by_remote_type.sort_values(by="job_count", ascending=False)

jobs_by_remote_type

  remote_type  job_count
0      Hybrid      16984
1      Onsite      16538
2      Remote      16478

In [31]:
salary_by_remote_type = ai_jobs.groupby("remote_type")["salary_avg_usd"].mean().reset_index()

salary_by_remote_type.columns = ["remote_type", "avg_salary_usd"]

salary_by_remote_type = salary_by_remote_type.sort_values(by="avg_salary_usd", ascending=False)

salary_by_remote_type

  remote_type  avg_salary_usd
0      Hybrid   111169.122969
2      Remote   110910.661033
1      Onsite   110506.855091

In [32]:
top_skills = skills_demand.groupby("skill")["job_id"].count().reset_index()

top_skills.columns = ["skill", "demand_count"]

top_skills = top_skills.sort_values(by="demand_count", ascending=False)

top_skills

              skill  demand_count
0               AWS         20638
10       TensorFlow         20552
3               GCP         20552
1             Azure         20517
9      Scikit-learn         20511
4               NLP         20414
6            Python         20396
8               SQL         20322
2   Computer Vision         20313
7                 R         20205
5           PyTorch         20185

In [33]:
skill_category_demand = skills_demand.groupby("skill_category")["job_id"].count().reset_index()

skill_category_demand.columns = ["skill_category", "demand_count"]

skill_category_demand = skill_category_demand.sort_values(by="demand_count", ascending=False)

skill_category_demand

  skill_category  demand_count
1             ML        101975
0          Cloud         61707
2    Programming         60923

In [34]:
skill_level_demand = skills_demand.groupby("skill_level")["job_id"].count().reset_index()

skill_level_demand.columns = ["skill_level", "demand_count"]

skill_level_demand = skill_level_demand.sort_values(by="demand_count", ascending=False)

skill_level_demand

    skill_level  demand_count
1         Basic         74992
2  Intermediate         74920
0      Advanced         74693

In [35]:
analysis_dir = PROCESSED_DATA_DIR / "analysis_tables"
analysis_dir.mkdir(exist_ok=True)

jobs_by_year.to_csv(analysis_dir / "jobs_by_year.csv", index=False)
jobs_by_country.to_csv(analysis_dir / "jobs_by_country.csv", index=False)
jobs_by_role.to_csv(analysis_dir / "jobs_by_role.csv", index=False)
salary_by_role.to_csv(analysis_dir / "salary_by_role.csv", index=False)
salary_by_country.to_csv(analysis_dir / "salary_by_country.csv", index=False)
salary_by_career_stage.to_csv(analysis_dir / "salary_by_career_stage.csv", index=False)
jobs_by_remote_type.to_csv(analysis_dir / "jobs_by_remote_type.csv", index=False)
salary_by_remote_type.to_csv(analysis_dir / "salary_by_remote_type.csv", index=False)
top_skills.to_csv(analysis_dir / "top_skills.csv", index=False)
skill_category_demand.to_csv(analysis_dir / "skill_category_demand.csv", index=False)
skill_level_demand.to_csv(analysis_dir / "skill_level_demand.csv", index=False)

print("Analysis tables saved successfully")

Analysis tables saved successfully