# 02 Feature Engineering

This notebook loads the cleaned processed datasets and creates analytical features for exploratory analysis and Power BI dashboard development. It adds average salary, salary level, career stage, remote-friendly status, and role group columns, then saves the feature-engineered dataset back to the processed data folder.

In [1]:
from pathlib import Path
import pandas as pd

def find_project_root(start_path):
    for path in [start_path, *start_path.parents]:
        if (path / "data" / "processed").exists():
            return path
    raise FileNotFoundError("Could not find project root with data/processed folder.")

BASE_DIR = find_project_root(Path.cwd())
PROCESSED_DATA_DIR = BASE_DIR / "data" / "processed"

ai_jobs = pd.read_csv(PROCESSED_DATA_DIR / "ai_jobs_cleaned.csv")
skills_demand = pd.read_csv(PROCESSED_DATA_DIR / "skills_demand_cleaned.csv")
country_trends = pd.read_csv(PROCESSED_DATA_DIR / "country_trends_cleaned.csv")

print("Cleaned datasets loaded successfully")
print("ai_jobs:", ai_jobs.shape)
print("skills_demand:", skills_demand.shape)
print("country_trends:", country_trends.shape)

Cleaned datasets loaded successfully
ai_jobs: (50000, 19)
skills_demand: (224605, 4)
country_trends: (42, 6)

In [2]:
print("ai_jobs data types:")
print(ai_jobs.dtypes)

print("\nskills_demand data types:")
print(skills_demand.dtypes)

print("\ncountry_trends data types:")
print(country_trends.dtypes)

ai_jobs data types:
job_id                      str
job_title                   str
company_type                str
industry                    str
country                     str
city                        str
remote_type                 str
experience_level            str
min_experience_years      int64
salary_min_usd            int64
salary_max_usd            int64
employment_type             str
posted_year               int64
company_size                str
salary_avg_usd          float64
salary_level                str
career_stage                str
is_remote_friendly          str
role_group                  str
dtype: object

skills_demand data types:
job_id            str
skill             str
skill_category    str
skill_level       str
dtype: object

country_trends data types:
country                str
year                 int64
total_ai_jobs        int64
avg_salary_usd       int64
remote_percentage    int64
top_skill              str
dtype: object

In [3]:
ai_jobs["salary_avg_usd"] = (ai_jobs["salary_min_usd"] + ai_jobs["salary_max_usd"]) / 2

def categorize_salary(salary):
    if salary < 80000:
        return "Low"
    elif salary < 120000:
        return "Medium"
    elif salary < 150000:
        return "High"
    else:
        return "Very High"

ai_jobs["salary_level"] = ai_jobs["salary_avg_usd"].apply(categorize_salary)

ai_jobs[["salary_min_usd", "salary_max_usd", "salary_avg_usd", "salary_level"]].head()

   salary_min_usd  salary_max_usd  salary_avg_usd salary_level
0           56873           72223         64548.0          Low
1           54803           85599         70201.0          Low
2          149980          175806        162893.0    Very High
3           53483           86477         69980.0          Low
4          102977          127298        115137.5       Medium

In [4]:
def create_career_stage(level):
    if level == "Entry":
        return "Entry Level"
    elif level == "Mid":
        return "Mid Level"
    elif level == "Senior":
        return "Senior Level"
    else:
        return "Unknown"

ai_jobs["career_stage"] = ai_jobs["experience_level"].apply(create_career_stage)

ai_jobs[["experience_level", "career_stage"]].head()

  experience_level  career_stage
0            Entry   Entry Level
1            Entry   Entry Level
2           Senior  Senior Level
3            Entry   Entry Level
4              Mid     Mid Level

In [5]:
def remote_friendly(remote_type):
    if remote_type in ["Remote", "Hybrid"]:
        return "Yes"
    elif remote_type == "Onsite":
        return "No"
    else:
        return "Unknown"

ai_jobs["is_remote_friendly"] = ai_jobs["remote_type"].apply(remote_friendly)

ai_jobs[["remote_type", "is_remote_friendly"]].head()

  remote_type is_remote_friendly
0      Remote                Yes
1      Remote                Yes
2      Remote                Yes
3      Remote                Yes
4      Hybrid                Yes

In [6]:
def create_role_group(job_title):
    if job_title == "Data Analyst":
        return "Data Analytics"
    elif job_title == "Data Scientist":
        return "Data Science"
    elif job_title == "Machine Learning Engineer":
        return "Machine Learning"
    elif job_title == "MLOps Engineer":
        return "MLOps"
    elif job_title == "AI Researcher":
        return "AI Research"
    elif job_title == "Applied Scientist":
        return "Applied AI / Research"
    else:
        return "Other"

ai_jobs["role_group"] = ai_jobs["job_title"].apply(create_role_group)

ai_jobs[["job_title", "role_group"]].head()

                   job_title             role_group
0             MLOps Engineer                  MLOps
1               Data Analyst         Data Analytics
2             MLOps Engineer                  MLOps
3          Applied Scientist  Applied AI / Research
4  Machine Learning Engineer       Machine Learning

In [7]:
feature_columns = [
    "salary_avg_usd",
    "salary_level",
    "career_stage",
    "is_remote_friendly",
    "role_group"
]

print("Feature columns added:")
print(ai_jobs[feature_columns].head())

print("\nMissing values in feature columns:")
print(ai_jobs[feature_columns].isnull().sum())

Feature columns added:
   salary_avg_usd salary_level  career_stage is_remote_friendly  \
0         64548.0          Low   Entry Level                Yes
1         70201.0          Low   Entry Level                Yes
2        162893.0    Very High  Senior Level                Yes
3         69980.0          Low   Entry Level                Yes
4        115137.5       Medium     Mid Level                Yes

              role_group
0                  MLOps
1         Data Analytics
2                  MLOps
3  Applied AI / Research
4       Machine Learning

Missing values in feature columns:
salary_avg_usd        0
salary_level          0
career_stage          0
is_remote_friendly    0
role_group            0
dtype: int64

In [8]:
ai_jobs.to_csv(PROCESSED_DATA_DIR / "ai_jobs_cleaned.csv", index=False)
skills_demand.to_csv(PROCESSED_DATA_DIR / "skills_demand_cleaned.csv", index=False)
country_trends.to_csv(PROCESSED_DATA_DIR / "country_trends_cleaned.csv", index=False)

print("Feature-engineered datasets saved successfully")
print("ai_jobs:", ai_jobs.shape)
print("skills_demand:", skills_demand.shape)
print("country_trends:", country_trends.shape)

Feature-engineered datasets saved successfully
ai_jobs: (50000, 19)
skills_demand: (224605, 4)
country_trends: (42, 6)

## Feature Engineering Summary

The cleaned job dataset now includes salary, career stage, remote-friendly, and role-group features. These processed files are ready for exploratory analysis, dashboard tables, and Power BI export.